# =========== Default ===========
[[colors.indexed_colors]]
color = "0xff9e64"
index = 16

[[colors.indexed_colors]]
color = "0xdb4b4b"
index = 17

[colors.bright]
black = "0x414868"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[colors.normal]
black = "0x15161E"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xa9b1d6"
yellow = "0xe0af68"

[colors.primary]
background = "0x1a1b26"
foreground = "0xc0caf5"

# =========== End Default ===========

# =========== Start Nightfox Alacritty Colors ===========
## name: dawnfox
## upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/dawnfox/alacritty.toml

# [colors.primary]
# background = "#faf4ed"
# foreground = "#575279"
# dim_foreground = "#4c4769"
# bright_foreground = "#625c87"

# [colors.cursor]
# text = "#575279"
# cursor = "#625c87"

# [colors.vi_mode_cursor]
# text = "#575279"
# cursor = "#56949f"

# [colors.search.matches]
# foreground = "#575279"
# background = "#b8cece"

# [colors.search.focused_match]
# foreground = "#575279"
# background = "#618774"

# [colors.footer_bar]
# foreground = "#575279"
# background = "#ebdfe4"

# [colors.hints.start]
# foreground = "#575279"
# background = "#d7827e"

# [colors.hints.end]
# foreground = "#575279"
# background = "#ebdfe4"

# [colors.selection]
# text = "#575279"
# background = "#d0d8d8"

# [colors.normal]
# black = "#575279"
# red = "#b4637a"
# green = "#618774"
# yellow = "#ea9d34"
# blue = "#286983"
# magenta = "#907aa9"
# cyan = "#56949f"
# white = "#e5e9f0"

# [colors.bright]
# black = "#5f5695"
# red = "#c26d85"
# green = "#629f81"
# yellow = "#eea846"
# blue = "#2d81a3"
# magenta = "#9a80b9"
# cyan = "#5ca7b4"
# white = "#e6ebf3"

# [colors.dim]
# black = "#504c6b"
# red = "#a5576d"
# green = "#597668"
# yellow = "#dd9024"
# blue = "#295e73"
# magenta = "#816b9a"
# cyan = "#50848c"
# white = "#c8cfde"

# [[colors.indexed_colors]]
# index = 16
# color = "#d7827e"

# [[colors.indexed_colors]]
# index = 17
# color = "#d685af"

# =========== End Nightfox Alacritty Colors ===========

# =========== Start Nightfox Alacritty Colors ===========
# Nightfox Alacritty Colors
## name: dayfox
## upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/dayfox/alacritty.toml

# [colors.primary]
# background = "#f6f2ee"
# foreground = "#3d2b5a"
# dim_foreground = "#302b5d"
# bright_foreground = "#643f61"

# [colors.cursor]
# text = "#3d2b5a"
# cursor = "#643f61"

# [colors.vi_mode_cursor]
# text = "#3d2b5a"
# cursor = "#287980"

# [colors.search.matches]
# foreground = "#3d2b5a"
# background = "#a4c1c2"

# [colors.search.focused_match]
# foreground = "#3d2b5a"
# background = "#396847"

# [colors.footer_bar]
# foreground = "#3d2b5a"
# background = "#d3c7bb"

# [colors.hints.start]
# foreground = "#3d2b5a"
# background = "#955f61"

# [colors.hints.end]
# foreground = "#3d2b5a"
# background = "#d3c7bb"

# [colors.selection]
# text = "#3d2b5a"
# background = "#e7d2be"

# [colors.normal]
# black = "#352c24"
# red = "#a5222f"
# green = "#396847"
# yellow = "#ac5402"
# blue = "#2848a9"
# magenta = "#6e33ce"
# cyan = "#287980"
# white = "#f2e9e1"

# [colors.bright]
# black = "#534c45"
# red = "#b3434e"
# green = "#577f63"
# yellow = "#b86e28"
# blue = "#4863b6"
# magenta = "#8452d5"
# cyan = "#488d93"
# white = "#f4ece6"

# [colors.dim]
# black = "#2d251f"
# red = "#8c1d28"
# green = "#30583c"
# yellow = "#924702"
# blue = "#223d90"
# magenta = "#5e2baf"
# cyan = "#22676d"
# white = "#cec6bf"

# [[colors.indexed_colors]]
# index = 16
# color = "#955f61"

# [[colors.indexed_colors]]
# index = 17
# color = "#a440b5"
# =========== End Nightfox Alacritty Colors ===========

[env]
TERM = "xterm-256color"

[font]
size = 11.5

[font.bold]
family = "InconsolataLGC Nerd Font"
style = "Bold"

[font.bold_italic]
family = "InconsolataLGC Nerd Font"
style = "Bold Italic"

[font.italic]
family = "InconsolataLGC Nerd Font"
style = "Italic"

[font.normal]
family = "InconsolataLGC Nerd Font"
style = "Regular"

[scrolling]
history = 10000

[window]
dynamic_padding = true
opacity = 0.87
# decorations = 'None' # When use VM Sway

[window.dimensions]
columns = 90
lines = 25

[window.padding]
x = 2
y = 2

[terminal.shell]
program = "zsh"



[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[keyboard]
